version: '3.2'

volumes:
  rabbitmqdata:
  rabbitmqlog:
  mariadb:

services:
  rabbitmq:
    image: rabbitmq:3-management-alpine
    environment:
      - RABBITMQ_DEFAULT_USER=wings
      - RABBITMQ_DEFAULT_PASS=wings
      - RABBITMQ_DEFAULT_VHOST=wings
    volumes:
      - rabbitmqdata:/var/lib/rabbitmq
      - rabbitmqlog:/var/log/rabbitmq

  mariadb:
    image: mariadb:10.6
    environment:
      - MARIADB_ROOT_PASSWORD=rootwings
      - MARIADB_DATABASE=wings
      - MARIADB_USER=wings
      - MARIADB_PASSWORD=wings
    volumes: # TODO: set external ip in zone_settings
      - mariadb:/var/lib/mysql
      - ./initdb-wings:/docker-entrypoint-initdb.d
      - ./sql-login:/sql-login
      - ./sql-wings:/sql-wings

  search:
    image: wings:latest
    depends_on:
      - mariadb
    volumes:
      - ./conf-docker:/wings/conf
    entrypoint: ["./topaz_search"]
    ports:
      - "54002:54002/tcp"
    restart: unless-stopped

  login:
    image: wings:latest
    depends_on:
      - rabbitmq
      - mariadb
    volumes:
      - ./conf-docker:/wings/conf
    entrypoint: ["./topaz_new_connect"]
    ports:
      - "54231:54231/tcp"
      - "54230:54230/tcp"
      - "54331:54331/tcp"
      - "54001:54001/tcp"
    restart: unless-stopped

  map:
    image: wings:latest
    depends_on:
      - rabbitmq
      - mariadb
    volumes:
      - ./conf-docker:/wings/conf
    entrypoint: ["./topaz_game"]
    ports:
      - "54230:54230/udp"
    restart: unless-stopped
