-- phpMyAdmin SQL Dump
-- version 4.9.7
-- https://www.phpmyadmin.net/
--
-- Host: 127.0.0.1
-- Generation Time: Feb 13, 2021 at 09:37 PM
-- Server version: 10.3.27-MariaDB-0+deb10u1
-- PHP Version: 7.3.19-1~deb10u1

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET AUTOCOMMIT = 0;
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Database: `topaz`
--

-- --------------------------------------------------------

--
-- Table structure for table `bcnm_info`
--

DROP TABLE IF EXISTS `bcnm_info`;
CREATE TABLE `bcnm_info` (
  `bcnmId` smallint(5) UNSIGNED NOT NULL,
  `zoneId` tinyint(3) UNSIGNED NOT NULL DEFAULT 0,
  `name` varchar(30) NOT NULL,
  `fastestName` varchar(15) DEFAULT 'Not Set!',
  `fastestPartySize` tinyint(2) UNSIGNED NOT NULL DEFAULT 0,
  `fastestTime` int(10) UNSIGNED DEFAULT 1,
  `previousName` varchar(15) DEFAULT 'Not Set!',
  `previousPartySize` tinyint(2) UNSIGNED NOT NULL DEFAULT 0,
  `previousTime` int(10) UNSIGNED DEFAULT 1,
  `timeLimit` smallint(5) UNSIGNED NOT NULL DEFAULT 1800,
  `levelCap` smallint(5) UNSIGNED NOT NULL DEFAULT 75,
  `partySize` smallint(5) UNSIGNED NOT NULL DEFAULT 6,
  `lootDropId` smallint(5) UNSIGNED NOT NULL DEFAULT 0,
  `rules` smallint(5) UNSIGNED NOT NULL DEFAULT 0,
  `isMission` tinyint(1) UNSIGNED NOT NULL DEFAULT 0
) ENGINE=InnoDB AVG_ROW_LENGTH=56 DEFAULT CHARSET=utf8;

--
-- Dumping data for table `bcnm_info`
--

INSERT INTO `bcnm_info` (`bcnmId`, `zoneId`, `name`, `fastestName`, `fastestPartySize`, `fastestTime`, `timeLimit`, `levelCap`, `partySize`, `lootDropId`, `rules`, `isMission`) VALUES(0, 139, 'rank_2_mission', 'nobody', 0, 1800, 1800, 25, 6, 0, 5, 1);
INSERT INTO `bcnm_info` (`bcnmId`, `zoneId`, `name`, `fastestName`, `fastestPartySize`, `fastestTime`, `timeLimit`, `levelCap`, `partySize`, `lootDropId`, `rules`, `isMission`) VALUES(1, 139, 'tails_of_woe', 'nobody', 0, 1800, 1800, 40, 6, 1, 15, 0);
INSERT INTO `bcnm_info` (`bcnmId`, `zoneId`, `name`, `fastestName`, `fastestPartySize`, `fastestTime`, `timeLimit`, `levelCap`, `partySize`, `lootDropId`, `rules`, `isMission`) VALUES(2, 139, 'dismemberment_brigade', 'nobody', 0, 1800, 1800, 60, 6, 2, 15, 0);
INSERT INTO `bcnm_info` (`bcnmId`, `zoneId`, `name`, `fastestName`, `fastestPartySize`, `fastestTime`, `timeLimit`, `levelCap`, `partySize`, `lootDropId`, `rules`, `isMission`) VALUES(3, 139, 'the_secret_weapon', 'nobody', 0, 1800, 1800, 75, 6, 0, 5, 1);
INSERT INTO `bcnm_info` (`bcnmId`, `zoneId`, `name`, `fastestName`, `fastestPartySize`, `fastestTime`, `timeLimit`, `levelCap`, `partySize`, `lootDropId`, `rules`, `isMission`) VALUES(4, 139, 'hostile_herbivores', 'nobody', 0, 1800, 1800, 50, 6, 4, 15, 0);
INSERT INTO `bcnm_info` (`bcnmId`, `zoneId`, `name`, `fastestName`, `fastestPartySize`, `fastestTime`, `timeLimit`, `levelCap`, `partySize`, `lootDropId`, `rules`, `isMission`) VALUES(5, 139, 'shattering_stars', 'nobody', 0, 600, 600, 99, 1, 0, 22, 0);
INSERT INTO `bcnm_info` (`bcnmId`, `zoneId`, `name`, `fastestName`, `fastestPartySize`, `fastestTime`, `timeLimit`, `levelCap`, `partySize`, `lootDropId`, `rules`, `isMission`) VALUES(6, 139, 'shattering_stars', 'nobody', 0, 600, 600, 99, 1, 0, 22, 0);
INSERT INTO `bcnm_info` (`bcnmId`, `zoneId`, `name`, `fastestName`, `fastestPartySize`, `fastestTime`, `timeLimit`, `levelCap`, `partySize`, `lootDropId`, `rules`, `isMission`) VALUES(7, 139, 'shattering_stars', 'nobody', 0, 600, 600, 99, 1, 0, 22, 0);
INSERT INTO `bcnm_info` (`bcnmId`, `zoneId`, `name`, `fastestName`, `fastestPartySize`, `fastestTime`, `timeLimit`, `levelCap`, `partySize`, `lootDropId`, `rules`, `isMission`) VALUES(8, 139, 'carapace_combatants', 'nobody', 0, 900, 900, 30, 3, 8, 15, 0);
INSERT INTO `bcnm_info` (`bcnmId`, `zoneId`, `name`, `fastestName`, `fastestPartySize`, `fastestTime`, `timeLimit`, `levelCap`, `partySize`, `lootDropId`, `rules`, `isMission`) VALUES(9, 139, 'shooting_fish', 'nobody', 0, 900, 900, 20, 3, 9, 15, 0);
INSERT INTO `bcnm_info` (`bcnmId`, `zoneId`, `name`, `fastestName`, `fastestPartySize`, `fastestTime`, `timeLimit`, `levelCap`, `partySize`, `lootDropId`, `rules`, `isMission`) VALUES(10, 139, 'dropping_like_flies', 'nobody', 0, 1800, 1800, 30, 6, 10, 15, 0);
INSERT INTO `bcnm_info` (`bcnmId`, `zoneId`, `name`, `fastestName`, `fastestPartySize`, `fastestTime`, `timeLimit`, `levelCap`, `partySize`, `lootDropId`, `rules`, `isMission`) VALUES(11, 139, 'horns_of_war', 'nobody', 0, 1800, 1800, 0, 18, 11, 15, 0);
INSERT INTO `bcnm_info` (`bcnmId`, `zoneId`, `name`, `fastestName`, `fastestPartySize`, `fastestTime`, `timeLimit`, `levelCap`, `partySize`, `lootDropId`, `rules`, `isMission`) VALUES(12, 139, 'under_observation', 'nobody', 0, 900, 900, 40, 3, 12, 15, 0);
INSERT INTO `bcnm_info` (`bcnmId`, `zoneId`, `name`, `fastestName`, `fastestPartySize`, `fastestTime`, `timeLimit`, `levelCap`, `partySize`, `lootDropId`, `rules`, `isMission`) VALUES(13, 139, 'eye_of_the_tiger', 'nobody', 0, 900, 900, 50, 3, 13, 15, 0);
INSERT INTO `bcnm_info` (`bcnmId`, `zoneId`, `name`, `fastestName`, `fastestPartySize`, `fastestTime`, `timeLimit`, `levelCap`, `partySize`, `lootDropId`, `rules`, `isMission`) VALUES(14, 139, 'shots_in_the_dark', 'nobody', 0, 900, 900, 60, 3, 14, 15, 0);
INSERT INTO `bcnm_info` (`bcnmId`, `zoneId`, `name`, `fastestName`, `fastestPartySize`, `fastestTime`, `timeLimit`, `levelCap`, `partySize`, `lootDropId`, `rules`, `isMission`) VALUES(15, 139, 'double_dragonian', 'nobody', 0, 1800, 1800, 0, 6, 15, 15, 0);
INSERT INTO `bcnm_info` (`bcnmId`, `zoneId`, `name`, `fastestName`, `fastestPartySize`, `fastestTime`, `timeLimit`, `levelCap`, `partySize`, `lootDropId`, `rules`, `isMission`) VALUES(16, 139, 'todays_horoscope', 'nobody', 0, 1800, 1800, 0, 6, 16, 15, 0);
INSERT INTO `bcnm_info` (`bcnmId`, `zoneId`, `name`, `fastestName`, `fastestPartySize`, `fastestTime`, `timeLimit`, `levelCap`, `partySize`, `lootDropId`, `rules`, `isMission`) VALUES(17, 139, 'contaminated_colosseum', 'nobody', 0, 1800, 1800, 0, 6, 17, 15, 0);
INSERT INTO `bcnm_info` (`bcnmId`, `zoneId`, `name`, `fastestName`, `fastestPartySize`, `fastestTime`, `timeLimit`, `levelCap`, `partySize`, `lootDropId`, `rules`, `isMission`) VALUES(18, 139, 'kindergarten_cap', 'nobody', 0, 900, 900, 0, 3, 18, 15, 0);
INSERT INTO `bcnm_info` (`bcnmId`, `zoneId`, `name`, `fastestName`, `fastestPartySize`, `fastestTime`, `timeLimit`, `levelCap`, `partySize`, `lootDropId`, `rules`, `isMission`) VALUES(19, 139, 'last_orc-shunned_hero', 'nobody', 0, 1800, 1800, 0, 6, 19, 15, 0);
INSERT INTO `bcnm_info` (`bcnmId`, `zoneId`, `name`, `fastestName`, `fastestPartySize`, `fastestTime`, `timeLimit`, `levelCap`, `partySize`, `lootDropId`, `rules`, `isMission`) VALUES(20, 139, 'beyond_infinity', 'nobody', 0, 600, 600, 0, 6, 0, 6, 0);
INSERT INTO `bcnm_info` (`bcnmId`, `zoneId`, `name`, `fastestName`, `fastestPartySize`, `fastestTime`, `timeLimit`, `levelCap`, `partySize`, `lootDropId`, `rules`, `isMission`) VALUES(32, 140, 'save_the_children', 'nobody', 0, 600, 600, 99, 6, 0, 5, 0);
INSERT INTO `bcnm_info` (`bcnmId`, `zoneId`, `name`, `fastestName`, `fastestPartySize`, `fastestTime`, `timeLimit`, `levelCap`, `partySize`, `lootDropId`, `rules`, `isMission`) VALUES(33, 140, 'holy_crest', 'nobody', 0, 600, 900, 0, 6, 0, 7, 0);
INSERT INTO `bcnm_info` (`bcnmId`, `zoneId`, `name`, `fastestName`, `fastestPartySize`, `fastestTime`, `timeLimit`, `levelCap`, `partySize`, `lootDropId`, `rules`, `isMission`) VALUES(34, 140, 'wings_of_fury', 'nobody', 0, 900, 900, 20, 3, 34, 15, 0);
INSERT INTO `bcnm_info` (`bcnmId`, `zoneId`, `name`, `fastestName`, `fastestPartySize`, `fastestTime`, `timeLimit`, `levelCap`, `partySize`, `lootDropId`, `rules`, `isMission`) VALUES(35, 140, 'petrifying_pair', 'nobody', 0, 900, 900, 30, 3, 35, 15, 0);
INSERT INTO `bcnm_info` (`bcnmId`, `zoneId`, `name`, `fastestName`, `fastestPartySize`, `fastestTime`, `timeLimit`, `levelCap`, `partySize`, `lootDropId`, `rules`, `isMission`) VALUES(36, 140, 'toadal_recall', 'nobody', 0, 1800, 1800, 30, 6, 36, 15, 0);
INSERT INTO `bcnm_info` (`bcnmId`, `zoneId`, `name`, `fastestName`, `fastestPartySize`, `fastestTime`, `timeLimit`, `levelCap`, `partySize`, `lootDropId`, `rules`, `isMission`) VALUES(37, 140, 'mirror_mirror', 'nobody', 0, 900, 900, 40, 3, 0, 7, 0);
INSERT INTO `bcnm_info` (`bcnmId`, `zoneId`, `name`, `fastestName`, `fastestPartySize`, `fastestTime`, `timeLimit`, `levelCap`, `partySize`, `lootDropId`, `rules`, `isMission`) VALUES(64, 144, 'rank_2_mission', 'nobody', 0, 1800, 1800, 25, 6, 0, 5, 1);
INSERT INTO `bcnm_info` (`bcnmId`, `zoneId`, `name`, `fastestName`, `fastestPartySize`, `fastestTime`, `timeLimit`, `levelCap`, `partySize`, `lootDropId`, `rules`, `isMission`) VALUES(65, 144, 'worms_turn', 'nobody', 0, 1800, 1800, 40, 6, 65, 15, 0);
INSERT INTO `bcnm_info` (`bcnmId`, `zoneId`, `name`, `fastestName`, `fastestPartySize`, `fastestTime`, `timeLimit`, `levelCap`, `partySize`, `lootDropId`, `rules`, `isMission`) VALUES(66, 144, 'grimshell_shocktroopers', 'nobody', 0, 1800, 1800, 60, 6, 66, 15, 0);
INSERT INTO `bcnm_info` (`bcnmId`, `zoneId`, `name`, `fastestName`, `fastestPartySize`, `fastestTime`, `timeLimit`, `levelCap`, `partySize`, `lootDropId`, `rules`, `isMission`) VALUES(67, 144, 'on_my_way', 'nobody', 0, 1800, 1800, 75, 6, 0, 5, 1);
INSERT INTO `bcnm_info` (`bcnmId`, `zoneId`, `name`, `fastestName`, `fastestPartySize`, `fastestTime`, `timeLimit`, `levelCap`, `partySize`, `lootDropId`, `rules`, `isMission`) VALUES(68, 144, 'thief_in_norg', 'nobody', 0, 1800, 1800, 0, 6, 0, 7, 0);
INSERT INTO `bcnm_info` (`bcnmId`, `zoneId`, `name`, `fastestName`, `fastestPartySize`, `fastestTime`, `timeLimit`, `levelCap`, `partySize`, `lootDropId`, `rules`, `isMission`) VALUES(69, 144, '3_2_1', 'nobody', 0, 1800, 1800, 50, 6, 69, 15, 0);
INSERT INTO `bcnm_info` (`bcnmId`, `zoneId`, `name`, `fastestName`, `fastestPartySize`, `fastestTime`, `timeLimit`, `levelCap`, `partySize`, `lootDropId`, `rules`, `isMission`) VALUES(70, 144, 'shattering_stars', 'nobody', 0, 600, 600, 99, 1, 0, 22, 0);
INSERT INTO `bcnm_info` (`bcnmId`, `zoneId`, `name`, `fastestName`, `fastestPartySize`, `fastestTime`, `timeLimit`, `levelCap`, `partySize`, `lootDropId`, `rules`, `isMission`) VALUES(71, 144, 'shattering_stars', 'nobody', 0, 600, 600, 99, 1, 0, 22, 0);
INSERT INTO `bcnm_info` (`bcnmId`, `zoneId`, `name`, `fastestName`, `fastestPartySize`, `fastestTime`, `timeLimit`, `levelCap`, `partySize`, `lootDropId`, `rules`, `isMission`) VALUES(72, 144, 'shattering_stars', 'nobody', 0, 600, 600, 99, 1, 0, 22, 0);
INSERT INTO `bcnm_info` (`bcnmId`, `zoneId`, `name`, `fastestName`, `fastestPartySize`, `fastestTime`, `timeLimit`, `levelCap`, `partySize`, `lootDropId`, `rules`, `isMission`) VALUES(73, 144, 'birds_of_a_feather', 'nobody', 0, 900, 900, 30, 3, 73, 15, 0);
INSERT INTO `bcnm_info` (`bcnmId`, `zoneId`, `name`, `fastestName`, `fastestPartySize`, `fastestTime`, `timeLimit`, `levelCap`, `partySize`, `lootDropId`, `rules`, `isMission`) VALUES(74, 144, 'crustacean_conundrum', 'nobody', 0, 900, 900, 20, 3, 74, 15, 0);
INSERT INTO `bcnm_info` (`bcnmId`, `zoneId`, `name`, `fastestName`, `fastestPartySize`, `fastestTime`, `timeLimit`, `levelCap`, `partySize`, `lootDropId`, `rules`, `isMission`) VALUES(75, 144, 'grove_guardians', 'nobody', 0, 1800, 1800, 30, 6, 75, 15, 0);
INSERT INTO `bcnm_info` (`bcnmId`, `zoneId`, `name`, `fastestName`, `fastestPartySize`, `fastestTime`, `timeLimit`, `levelCap`, `partySize`, `lootDropId`, `rules`, `isMission`) VALUES(76, 144, 'hills_are_alive', 'nobody', 0, 1800, 1800, 0, 18, 76, 15, 0);
INSERT INTO `bcnm_info` (`bcnmId`, `zoneId`, `name`, `fastestName`, `fastestPartySize`, `fastestTime`, `timeLimit`, `levelCap`, `partySize`, `lootDropId`, `rules`, `isMission`) VALUES(77, 144, 'royal_jelly', 'nobody', 0, 900, 900, 40, 3, 77, 15, 0);
INSERT INTO `bcnm_info` (`bcnmId`, `zoneId`, `name`, `fastestName`, `fastestPartySize`, `fastestTime`, `timeLimit`, `levelCap`, `partySize`, `lootDropId`, `rules`, `isMission`) VALUES(78, 144, 'final_bout', 'nobody', 0, 180, 180, 50, 3, 78, 15, 0);
INSERT INTO `bcnm_info` (`bcnmId`, `zoneId`, `name`, `fastestName`, `fastestPartySize`, `fastestTime`, `timeLimit`, `levelCap`, `partySize`, `lootDropId`, `rules`, `isMission`) VALUES(79, 144, 'up_in_arms', 'nobody', 0, 900, 900, 60, 3, 79, 15, 0);
INSERT INTO `bcnm_info` (`bcnmId`, `zoneId`, `name`, `fastestName`, `fastestPartySize`, `fastestTime`, `timeLimit`, `levelCap`, `partySize`, `lootDropId`, `rules`, `isMission`) VALUES(80, 144, 'copycat', 'nobody', 0, 1800, 1800, 0, 6, 80, 15, 0);
INSERT INTO `bcnm_info` (`bcnmId`, `zoneId`, `name`, `fastestName`, `fastestPartySize`, `fastestTime`, `timeLimit`, `levelCap`, `partySize`, `lootDropId`, `rules`, `isMission`) VALUES(81, 144, 'operation_desert_swarm', 'nobody', 0, 1800, 1800, 0, 6, 81, 15, 0);
INSERT INTO `bcnm_info` (`bcnmId`, `zoneId`, `name`, `fastestName`, `fastestPartySize`, `fastestTime`, `timeLimit`, `levelCap`, `partySize`, `lootDropId`, `rules`, `isMission`) VALUES(82, 144, 'prehistoric_pigeons', 'nobody', 0, 1800, 1800, 0, 6, 82, 15, 0);
INSERT INTO `bcnm_info` (`bcnmId`, `zoneId`, `name`, `fastestName`, `fastestPartySize`, `fastestTime`, `timeLimit`, `levelCap`, `partySize`, `lootDropId`, `rules`, `isMission`) VALUES(83, 144, 'palborough_project', 'nobody', 0, 900, 900, 0, 3, 83, 15, 0);
INSERT INTO `bcnm_info` (`bcnmId`, `zoneId`, `name`, `fastestName`, `fastestPartySize`, `fastestTime`, `timeLimit`, `levelCap`, `partySize`, `lootDropId`, `rules`, `isMission`) VALUES(84, 144, 'shell_shocked', 'nobody', 0, 1800, 1800, 0, 6, 84, 15, 0);
INSERT INTO `bcnm_info` (`bcnmId`, `zoneId`, `name`, `fastestName`, `fastestPartySize`, `fastestTime`, `timeLimit`, `levelCap`, `partySize`, `lootDropId`, `rules`, `isMission`) VALUES(85, 144, 'beyond_infinity', 'nobody', 0, 600, 600, 99, 6, 0, 6, 0);
INSERT INTO `bcnm_info` (`bcnmId`, `zoneId`, `name`, `fastestName`, `fastestPartySize`, `fastestTime`, `timeLimit`, `levelCap`, `partySize`, `lootDropId`, `rules`, `isMission`) VALUES(96, 146, 'rank_2_mission', 'nobody', 0, 1800, 1800, 25, 6, 0, 5, 1);
INSERT INTO `bcnm_info` (`bcnmId`, `zoneId`, `name`, `fastestName`, `fastestPartySize`, `fastestTime`, `timeLimit`, `levelCap`, `partySize`, `lootDropId`, `rules`, `isMission`) VALUES(97, 146, 'steamed_sprouts', 'nobody', 0, 1800, 1800, 40, 6, 97, 15, 0);
INSERT INTO `bcnm_info` (`bcnmId`, `zoneId`, `name`, `fastestName`, `fastestPartySize`, `fastestTime`, `timeLimit`, `levelCap`, `partySize`, `lootDropId`, `rules`, `isMission`) VALUES(98, 146, 'divine_punishers', 'nobody', 0, 1800, 1800, 60, 6, 98, 15, 0);
INSERT INTO `bcnm_info` (`bcnmId`, `zoneId`, `name`, `fastestName`, `fastestPartySize`, `fastestTime`, `timeLimit`, `levelCap`, `partySize`, `lootDropId`, `rules`, `isMission`) VALUES(99, 146, 'saintly_invitation', 'nobody', 0, 1800, 1800, 75, 6, 0, 5, 1);
INSERT INTO `bcnm_info` (`bcnmId`, `zoneId`, `name`, `fastestName`, `fastestPartySize`, `fastestTime`, `timeLimit`, `levelCap`, `partySize`, `lootDropId`, `rules`, `isMission`) VALUES(100, 146, 'treasure_and_tribulations', 'nobody', 0, 1800, 1800, 50, 6, 100, 15, 0);
INSERT INTO `bcnm_info` (`bcnmId`, `zoneId`, `name`, `fastestName`, `fastestPartySize`, `fastestTime`, `timeLimit`, `levelCap`, `partySize`, `lootDropId`, `rules`, `isMission`) VALUES(101, 146, 'shattering_stars', 'nobody', 0, 600, 600, 99, 1, 0, 22, 0);
INSERT INTO `bcnm_info` (`bcnmId`, `zoneId`, `name`, `fastestName`, `fastestPartySize`, `fastestTime`, `timeLimit`, `levelCap`, `partySize`, `lootDropId`, `rules`, `isMission`) VALUES(102, 146, 'shattering_stars', 'nobody', 0, 600, 600, 99, 1, 0, 22, 0);
INSERT INTO `bcnm_info` (`bcnmId`, `zoneId`, `name`, `fastestName`, `fastestPartySize`, `fastestTime`, `timeLimit`, `levelCap`, `partySize`, `lootDropId`, `rules`, `isMission`) VALUES(103, 146, 'shattering_stars', 'nobody', 0, 600, 600, 99, 1, 0, 22, 0);
INSERT INTO `bcnm_info` (`bcnmId`, `zoneId`, `name`, `fastestName`, `fastestPartySize`, `fastestTime`, `timeLimit`, `levelCap`, `partySize`, `lootDropId`, `rules`, `isMission`) VALUES(104, 146, 'creeping_doom', 'nobody', 0, 900, 900, 30, 3, 104, 15, 0);
INSERT INTO `bcnm_info` (`bcnmId`, `zoneId`, `name`, `fastestName`, `fastestPartySize`, `fastestTime`, `timeLimit`, `levelCap`, `partySize`, `lootDropId`, `rules`, `isMission`) VALUES(105, 146, 'charming_trio', 'nobody', 0, 900, 900, 20, 3, 105, 15, 0);
INSERT INTO `bcnm_info` (`bcnmId`, `zoneId`, `name`, `fastestName`, `fastestPartySize`, `fastestTime`, `timeLimit`, `levelCap`, `partySize`, `lootDropId`, `rules`, `isMission`) VALUES(106, 146, 'harem_scarem', 'nobody', 0, 1800, 1800, 30, 6, 106, 15, 0);
INSERT INTO `bcnm_info` (`bcnmId`, `zoneId`, `name`, `fastestName`, `fastestPartySize`, `fastestTime`, `timeLimit`, `levelCap`, `partySize`, `lootDropId`, `rules`, `isMission`) VALUES(107, 146, 'early_bird_catches_the_wyrm', 'nobody', 0, 1800, 1800, 0, 18, 107, 15, 0);
INSERT INTO `bcnm_info` (`bcnmId`, `zoneId`, `name`, `fastestName`, `fastestPartySize`, `fastestTime`, `timeLimit`, `levelCap`, `partySize`, `lootDropId`, `rules`, `isMission`) VALUES(108, 146, 'royal_succession', 'nobody', 0, 900, 900, 40, 3, 108, 15, 0);
INSERT INTO `bcnm_info` (`bcnmId`, `zoneId`, `name`, `fastestName`, `fastestPartySize`, `fastestTime`, `timeLimit`, `levelCap`, `partySize`, `lootDropId`, `rules`, `isMission`) VALUES(109, 146, 'rapid_raptors', 'nobody', 0, 900, 900, 50, 3, 109, 15, 0);
INSERT INTO `bcnm_info` (`bcnmId`, `zoneId`, `name`, `fastestName`, `fastestPartySize`, `fastestTime`, `timeLimit`, `levelCap`, `partySize`, `lootDropId`, `rules`, `isMission`) VALUES(110, 146, 'wild_wild_whiskers', 'nobody', 0, 900, 900, 60, 3, 110, 15, 0);
INSERT INTO `bcnm_info` (`bcnmId`, `zoneId`, `name`, `fastestName`, `fastestPartySize`, `fastestTime`, `timeLimit`, `levelCap`, `partySize`, `lootDropId`, `rules`, `isMission`) VALUES(111, 146, 'seasons_greetings', 'nobody', 0, 1800, 1800, 0, 6, 111, 15, 0);
INSERT INTO `bcnm_info` (`bcnmId`, `zoneId`, `name`, `fastestName`, `fastestPartySize`, `fastestTime`, `timeLimit`, `levelCap`, `partySize`, `lootDropId`, `rules`, `isMission`) VALUES(112, 146, 'royale_ramble', 'nobody', 0, 1800, 1800, 0, 6, 112, 15, 0);
INSERT INTO `bcnm_info` (`bcnmId`, `zoneId`, `name`, `fastestName`, `fastestPartySize`, `fastestTime`, `timeLimit`, `levelCap`, `partySize`, `lootDropId`, `rules`, `isMission`) VALUES(113, 146, 'moa_constrictors', 'nobody', 0, 1800, 1800, 0, 6, 113, 15, 0);
INSERT INTO `bcnm_info` (`bcnmId`, `zoneId`, `name`, `fastestName`, `fastestPartySize`, `fastestTime`, `timeLimit`, `levelCap`, `partySize`, `lootDropId`, `rules`, `isMission`) VALUES(114, 146, 'v_formation', 'nobody', 0, 900, 900, 0, 3, 114, 15, 0);
INSERT INTO `bcnm_info` (`bcnmId`, `zoneId`, `name`, `fastestName`, `fastestPartySize`, `fastestTime`, `timeLimit`, `levelCap`, `partySize`, `lootDropId`, `rules`, `isMission`) VALUES(115, 146, 'avian_apostates', 'nobody', 0, 1800, 1800, 0, 6, 115, 15, 0);
INSERT INTO `bcnm_info` (`bcnmId`, `zoneId`, `name`, `fastestName`, `fastestPartySize`, `fastestTime`, `timeLimit`, `levelCap`, `partySize`, `lootDropId`, `rules`, `isMission`) VALUES(116, 146, 'beyond_infinity', 'nobody', 0, 600, 600, 99, 6, 0, 6, 0);
INSERT INTO `bcnm_info` (`bcnmId`, `zoneId`, `name`, `fastestName`, `fastestPartySize`, `fastestTime`, `timeLimit`, `levelCap`, `partySize`, `lootDropId`, `rules`, `isMission`) VALUES(128, 163, 'temple_of_uggalepih', 'nobody', 0, 1800, 1800, 75, 6, 0, 5, 1);
INSERT INTO `bcnm_info` (`bcnmId`, `zoneId`, `name`, `fastestName`, `fastestPartySize`, `fastestTime`, `timeLimit`, `levelCap`, `partySize`, `lootDropId`, `rules`, `isMission`) VALUES(129, 163, 'jungle_boogymen', 'nobody', 0, 1800, 1800, 60, 6, 129, 15, 0);
INSERT INTO `bcnm_info` (`bcnmId`, `zoneId`, `name`, `fastestName`, `fastestPartySize`, `fastestTime`, `timeLimit`, `levelCap`, `partySize`, `lootDropId`, `rules`, `isMission`) VALUES(130, 163, 'amphibian_assault', 'nobody', 0, 1800, 1800, 60, 6, 130, 15, 0);
INSERT INTO `bcnm_info` (`bcnmId`, `zoneId`, `name`, `fastestName`, `fastestPartySize`, `fastestTime`, `timeLimit`, `levelCap`, `partySize`, `lootDropId`, `rules`, `isMission`) VALUES(131, 163, 'project_shantottofication', 'nobody', 0, 1800, 1800, 99, 6, 0, 5, 1);
INSERT INTO `bcnm_info` (`bcnmId`, `zoneId`, `name`, `fastestName`, `fastestPartySize`, `fastestTime`, `timeLimit`, `levelCap`, `partySize`, `lootDropId`, `rules`, `isMission`) VALUES(132, 163, 'whom_wilt_thou_call', 'nobody', 0, 1800, 1800, 0, 6, 132, 15, 0);
INSERT INTO `bcnm_info` (`bcnmId`, `zoneId`, `name`, `fastestName`, `fastestPartySize`, `fastestTime`, `timeLimit`, `levelCap`, `partySize`, `lootDropId`, `rules`, `isMission`) VALUES(160, 165, 'shadow_lord_battle', 'nobody', 0, 1800, 1800, 75, 6, 0, 5, 1);
INSERT INTO `bcnm_info` (`bcnmId`, `zoneId`, `name`, `fastestName`, `fastestPartySize`, `fastestTime`, `timeLimit`, `levelCap`, `partySize`, `lootDropId`, `rules`, `isMission`) VALUES(161, 165, 'where_two_paths_converge', 'nobody', 0, 1800, 1800, 75, 6, 0, 5, 1);
INSERT INTO `bcnm_info` (`bcnmId`, `zoneId`, `name`, `fastestName`, `fastestPartySize`, `fastestTime`, `timeLimit`, `levelCap`, `partySize`, `lootDropId`, `rules`, `isMission`) VALUES(162, 165, 'kindred_spirits', 'nobody', 0, 1800, 1800, 60, 6, 162, 15, 0);
INSERT INTO `bcnm_info` (`bcnmId`, `zoneId`, `name`, `fastestName`, `fastestPartySize`, `fastestTime`, `timeLimit`, `levelCap`, `partySize`, `lootDropId`, `rules`, `isMission`) VALUES(163, 165, 'survival_of_the_wisest', 'nobody', 0, 600, 600, 99, 1, 0, 6, 0);
INSERT INTO `bcnm_info` (`bcnmId`, `zoneId`, `name`, `fastestName`, `fastestPartySize`, `fastestTime`, `timeLimit`, `levelCap`, `partySize`, `lootDropId`, `rules`, `isMission`) VALUES(164, 165, 'smash_a_malevolent_menace', 'nobody', 0, 1800, 1800, 75, 6, 0, 5, 1);
INSERT INTO `bcnm_info` (`bcnmId`, `zoneId`, `name`, `fastestName`, `fastestPartySize`, `fastestTime`, `timeLimit`, `levelCap`, `partySize`, `lootDropId`, `rules`, `isMission`) VALUES(192, 168, 'through_the_quicksand_caves', 'nobody', 0, 1800, 1800, 75, 6, 0, 5, 1);
INSERT INTO `bcnm_info` (`bcnmId`, `zoneId`, `name`, `fastestName`, `fastestPartySize`, `fastestTime`, `timeLimit`, `levelCap`, `partySize`, `lootDropId`, `rules`, `isMission`) VALUES(193, 168, 'legion_xi_comitatensis', 'nobody', 0, 1800, 1800, 60, 6, 193, 15, 0);
INSERT INTO `bcnm_info` (`bcnmId`, `zoneId`, `name`, `fastestName`, `fastestPartySize`, `fastestTime`, `timeLimit`, `levelCap`, `partySize`, `lootDropId`, `rules`, `isMission`) VALUES(194, 168, 'shattering_stars', 'nobody', 0, 600, 600, 99, 1, 0, 22, 0);
INSERT INTO `bcnm_info` (`bcnmId`, `zoneId`, `name`, `fastestName`, `fastestPartySize`, `fastestTime`, `timeLimit`, `levelCap`, `partySize`, `lootDropId`, `rules`, `isMission`) VALUES(195, 168, 'shattering_stars', 'nobody', 0, 600, 600, 99, 1, 0, 22, 0);
INSERT INTO `bcnm_info` (`bcnmId`, `zoneId`, `name`, `fastestName`, `fastestPartySize`, `fastestTime`, `timeLimit`, `levelCap`, `partySize`, `lootDropId`, `rules`, `isMission`) VALUES(196, 168, 'shattering_stars', 'nobody', 0, 600, 600, 99, 1, 0, 22, 0);
INSERT INTO `bcnm_info` (`bcnmId`, `zoneId`, `name`, `fastestName`, `fastestPartySize`, `fastestTime`, `timeLimit`, `levelCap`, `partySize`, `lootDropId`, `rules`, `isMission`) VALUES(197, 168, 'cactuar_suave', 'nobody', 0, 1800, 1800, 0, 6, 197, 15, 0);
INSERT INTO `bcnm_info` (`bcnmId`, `zoneId`, `name`, `fastestName`, `fastestPartySize`, `fastestTime`, `timeLimit`, `levelCap`, `partySize`, `lootDropId`, `rules`, `isMission`) VALUES(198, 168, 'eye_of_the_storm', 'nobody', 0, 1800, 1800, 0, 6, 198, 15, 0);
INSERT INTO `bcnm_info` (`bcnmId`, `zoneId`, `name`, `fastestName`, `fastestPartySize`, `fastestTime`, `timeLimit`, `levelCap`, `partySize`, `lootDropId`, `rules`, `isMission`) VALUES(199, 168, 'scarlet_king', 'nobody', 0, 1800, 1800, 0, 6, 199, 15, 0);
INSERT INTO `bcnm_info` (`bcnmId`, `zoneId`, `name`, `fastestName`, `fastestPartySize`, `fastestTime`, `timeLimit`, `levelCap`, `partySize`, `lootDropId`, `rules`, `isMission`) VALUES(200, 168, 'cat_burglar_bares_fangs', 'nobody', 0, 1800, 1800, 75, 6, 0, 5, 1);
INSERT INTO `bcnm_info` (`bcnmId`, `zoneId`, `name`, `fastestName`, `fastestPartySize`, `fastestTime`, `timeLimit`, `levelCap`, `partySize`, `lootDropId`, `rules`, `isMission`) VALUES(201, 168, 'dragon_scales', 'nobody', 0, 600, 600, 0, 1, 0, 6, 0);
INSERT INTO `bcnm_info` (`bcnmId`, `zoneId`, `name`, `fastestName`, `fastestPartySize`, `fastestTime`, `timeLimit`, `levelCap`, `partySize`, `lootDropId`, `rules`, `isMission`) VALUES(224, 170, 'moonlit_path', 'nobody', 0, 1800, 1800, 0, 6, 0, 5, 0);
INSERT INTO `bcnm_info` (`bcnmId`, `zoneId`, `name`, `fastestName`, `fastestPartySize`, `fastestTime`, `timeLimit`, `levelCap`, `partySize`, `lootDropId`, `rules`, `isMission`) VALUES(225, 170, 'moon_reading', 'nobody', 0, 1800, 1800, 75, 6, 0, 5, 1);
INSERT INTO `bcnm_info` (`bcnmId`, `zoneId`, `name`, `fastestName`, `fastestPartySize`, `fastestTime`, `timeLimit`, `levelCap`, `partySize`, `lootDropId`, `rules`, `isMission`) VALUES(226, 170, 'waking_the_beast_fullmoon', 'nobody', 0, 1800, 1800, 0, 18, 0, 5, 0);
INSERT INTO `bcnm_info` (`bcnmId`, `zoneId`, `name`, `fastestName`, `fastestPartySize`, `fastestTime`, `timeLimit`, `levelCap`, `partySize`, `lootDropId`, `rules`, `isMission`) VALUES(227, 170, 'battaru_royale', 'nobody', 0, 1800, 1800, 0, 6, 0, 5, 1);
INSERT INTO `bcnm_info` (`bcnmId`, `zoneId`, `name`, `fastestName`, `fastestPartySize`, `fastestTime`, `timeLimit`, `levelCap`, `partySize`, `lootDropId`, `rules`, `isMission`) VALUES(256, 179, 'return_to_delkfutts_tower', 'nobody', 0, 1800, 1800, 75, 6, 0, 5, 1);
INSERT INTO `bcnm_info` (`bcnmId`, `zoneId`, `name`, `fastestName`, `fastestPartySize`, `fastestTime`, `timeLimit`, `levelCap`, `partySize`, `lootDropId`, `rules`, `isMission`) VALUES(257, 179, 'indomitable_triumvirate_vs3', 'nobody', 0, 900, 900, 60, 6, 0, 4, 0);
INSERT INTO `bcnm_info` (`bcnmId`, `zoneId`, `name`, `fastestName`, `fastestPartySize`, `fastestTime`, `timeLimit`, `levelCap`, `partySize`, `lootDropId`, `rules`, `isMission`) VALUES(258, 179, 'dauntless_duo_vs2', 'nobody', 0, 900, 900, 60, 6, 0, 4, 0);
INSERT INTO `bcnm_info` (`bcnmId`, `zoneId`, `name`, `fastestName`, `fastestPartySize`, `fastestTime`, `timeLimit`, `levelCap`, `partySize`, `lootDropId`, `rules`, `isMission`) VALUES(259, 179, 'solitary_demolisher_vs1', 'nobody', 0, 900, 900, 60, 6, 0, 4, 0);
INSERT INTO `bcnm_info` (`bcnmId`, `zoneId`, `name`, `fastestName`, `fastestPartySize`, `fastestTime`, `timeLimit`, `levelCap`, `partySize`, `lootDropId`, `rules`, `isMission`) VALUES(260, 179, 'heroines_combat', 'nobody', 0, 900, 900, 60, 6, 0, 4, 0);
INSERT INTO `bcnm_info` (`bcnmId`, `zoneId`, `name`, `fastestName`, `fastestPartySize`, `fastestTime`, `timeLimit`, `levelCap`, `partySize`, `lootDropId`, `rules`, `isMission`) VALUES(261, 179, 'mercenary_camp', 'nobody', 0, 900, 900, 60, 6, 0, 4, 0);
INSERT INTO `bcnm_info` (`bcnmId`, `zoneId`, `name`, `fastestName`, `fastestPartySize`, `fastestTime`, `timeLimit`, `levelCap`, `partySize`, `lootDropId`, `rules`, `isMission`) VALUES(262, 179, 'ode_of_life_bestowing', 'nobody', 0, 1800, 1800, 0, 6, 0, 5, 1);
INSERT INTO `bcnm_info` (`bcnmId`, `zoneId`, `name`, `fastestName`, `fastestPartySize`, `fastestTime`, `timeLimit`, `levelCap`, `partySize`, `lootDropId`, `rules`, `isMission`) VALUES(288, 180, 'ark_angels_1', 'nobody', 0, 1800, 1800, 75, 6, 0, 5, 1);
INSERT INTO `bcnm_info` (`bcnmId`, `zoneId`, `name`, `fastestName`, `fastestPartySize`, `fastestTime`, `timeLimit`, `levelCap`, `partySize`, `lootDropId`, `rules`, `isMission`) VALUES(289, 180, 'ark_angels_2', 'nobody', 0, 1800, 1800, 75, 6, 0, 5, 1);
INSERT INTO `bcnm_info` (`bcnmId`, `zoneId`, `name`, `fastestName`, `fastestPartySize`, `fastestTime`, `timeLimit`, `levelCap`, `partySize`, `lootDropId`, `rules`, `isMission`) VALUES(290, 180, 'ark_angels_3', 'nobody', 0, 1800, 1800, 75, 6, 0, 5, 1);
INSERT INTO `bcnm_info` (`bcnmId`, `zoneId`, `name`, `fastestName`, `fastestPartySize`, `fastestTime`, `timeLimit`, `levelCap`, `partySize`, `lootDropId`, `rules`, `isMission`) VALUES(291, 180, 'ark_angels_4', 'nobody', 0, 1800, 1800, 75, 6, 0, 5, 1);
INSERT INTO `bcnm_info` (`bcnmId`, `zoneId`, `name`, `fastestName`, `fastestPartySize`, `fastestTime`, `timeLimit`, `levelCap`, `partySize`, `lootDropId`, `rules`, `isMission`) VALUES(292, 180, 'ark_angels_5', 'nobody', 0, 1800, 1800, 75, 6, 0, 5, 1);
INSERT INTO `bcnm_info` (`bcnmId`, `zoneId`, `name`, `fastestName`, `fastestPartySize`, `fastestTime`, `timeLimit`, `levelCap`, `partySize`, `lootDropId`, `rules`, `isMission`) VALUES(293, 180, 'divine_might', 'nobody', 0, 1800, 1800, 75, 18, 0, 5, 1);
INSERT INTO `bcnm_info` (`bcnmId`, `zoneId`, `name`, `fastestName`, `fastestPartySize`, `fastestTime`, `timeLimit`, `levelCap`, `partySize`, `lootDropId`, `rules`, `isMission`) VALUES(320, 181, 'celestial_nexus', 'nobody', 0, 1800, 1800, 75, 6, 0, 5, 1);
INSERT INTO `bcnm_info` (`bcnmId`, `zoneId`, `name`, `fastestName`, `fastestPartySize`, `fastestTime`, `timeLimit`, `levelCap`, `partySize`, `lootDropId`, `rules`, `isMission`) VALUES(352, 156, 'fiat_lux', 'nobody', 0, 1800, 1800, 0, 6, 352, 15, 0);
INSERT INTO `bcnm_info` (`bcnmId`, `zoneId`, `name`, `fastestName`, `fastestPartySize`, `fastestTime`, `timeLimit`, `levelCap`, `partySize`, `lootDropId`, `rules`, `isMission`) VALUES(353, 156, 'darkness_descends', 'nobody', 0, 1800, 1800, 99, 6, 0, 5, 0);
INSERT INTO `bcnm_info` (`bcnmId`, `zoneId`, `name`, `fastestName`, `fastestPartySize`, `fastestTime`, `timeLimit`, `levelCap`, `partySize`, `lootDropId`, `rules`, `isMission`) VALUES(354, 156, 'bonds_of_mythril', 'nobody', 0, 1800, 1800, 0, 18, 0, 5, 0);
INSERT INTO `bcnm_info` (`bcnmId`, `zoneId`, `name`, `fastestName`, `fastestPartySize`, `fastestTime`, `timeLimit`, `levelCap`, `partySize`, `lootDropId`, `rules`, `isMission`) VALUES(385, 182, 'maiden_of_the_dusk', 'nobody', 0, 1800, 1800, 99, 6, 0, 5, 0);
INSERT INTO `bcnm_info` (`bcnmId`, `zoneId`, `name`, `fastestName`, `fastestPartySize`, `fastestTime`, `timeLimit`, `levelCap`, `partySize`, `lootDropId`, `rules`, `isMission`) VALUES(388, 182, 'champion_of_the_dawn', 'nobody', 0, 1800, 1800, 0, 6, 0, 5, 0);
INSERT INTO `bcnm_info` (`bcnmId`, `zoneId`, `name`, `fastestName`, `fastestPartySize`, `fastestTime`, `timeLimit`, `levelCap`, `partySize`, `lootDropId`, `rules`, `isMission`) VALUES(416, 201, 'trial_by_wind', 'nobody', 0, 1800, 1800, 0, 6, 0, 5, 0);
INSERT INTO `bcnm_info` (`bcnmId`, `zoneId`, `name`, `fastestName`, `fastestPartySize`, `fastestTime`, `timeLimit`, `levelCap`, `partySize`, `lootDropId`, `rules`, `isMission`) VALUES(417, 201, 'carbuncle_debacle', 'nobody', 0, 1800, 1800, 0, 18, 0, 5, 0);
INSERT INTO `bcnm_info` (`bcnmId`, `zoneId`, `name`, `fastestName`, `fastestPartySize`, `fastestTime`, `timeLimit`, `levelCap`, `partySize`, `lootDropId`, `rules`, `isMission`) VALUES(418, 201, 'trial-size_trial_by_wind', 'nobody', 0, 900, 900, 20, 1, 0, 5, 0);
INSERT INTO `bcnm_info` (`bcnmId`, `zoneId`, `name`, `fastestName`, `fastestPartySize`, `fastestTime`, `timeLimit`, `levelCap`, `partySize`, `lootDropId`, `rules`, `isMission`) VALUES(419, 201, 'waking_the_beast', 'nobody', 0, 1800, 1800, 0, 18, 0, 5, 0);
INSERT INTO `bcnm_info` (`bcnmId`, `zoneId`, `name`, `fastestName`, `fastestPartySize`, `fastestTime`, `timeLimit`, `levelCap`, `partySize`, `lootDropId`, `rules`, `isMission`) VALUES(420, 201, 'sugar-coated_directive', 'nobody', 0, 1800, 1800, 99, 6, 0, 5, 0);
INSERT INTO `bcnm_info` (`bcnmId`, `zoneId`, `name`, `fastestName`, `fastestPartySize`, `fastestTime`, `timeLimit`, `levelCap`, `partySize`, `lootDropId`, `rules`, `isMission`) VALUES(448, 202, 'trial_by_lightning', 'nobody', 0, 1800, 1800, 0, 6, 0, 5, 0);
INSERT INTO `bcnm_info` (`bcnmId`, `zoneId`, `name`, `fastestName`, `fastestPartySize`, `fastestTime`, `timeLimit`, `levelCap`, `partySize`, `lootDropId`, `rules`, `isMission`) VALUES(449, 202, 'carbuncle_debacle', 'nobody', 0, 1800, 1800, 0, 18, 0, 5, 0);
INSERT INTO `bcnm_info` (`bcnmId`, `zoneId`, `name`, `fastestName`, `fastestPartySize`, `fastestTime`, `timeLimit`, `levelCap`, `partySize`, `lootDropId`, `rules`, `isMission`) VALUES(450, 202, 'trial-size_trial_by_lightning', 'nobody', 0, 900, 900, 20, 1, 0, 5, 0);
INSERT INTO `bcnm_info` (`bcnmId`, `zoneId`, `name`, `fastestName`, `fastestPartySize`, `fastestTime`, `timeLimit`, `levelCap`, `partySize`, `lootDropId`, `rules`, `isMission`) VALUES(451, 202, 'waking_the_beast', 'nobody', 0, 1800, 1800, 0, 18, 0, 5, 0);
INSERT INTO `bcnm_info` (`bcnmId`, `zoneId`, `name`, `fastestName`, `fastestPartySize`, `fastestTime`, `timeLimit`, `levelCap`, `partySize`, `lootDropId`, `rules`, `isMission`) VALUES(452, 202, 'sugar-coated_directive', 'nobody', 0, 1800, 1800, 99, 6, 0, 5, 0);
INSERT INTO `bcnm_info` (`bcnmId`, `zoneId`, `name`, `fastestName`, `fastestPartySize`, `fastestTime`, `timeLimit`, `levelCap`, `partySize`, `lootDropId`, `rules`, `isMission`) VALUES(480, 203, 'trial_by_ice', 'nobody', 0, 1800, 1800, 0, 6, 0, 5, 0);
INSERT INTO `bcnm_info` (`bcnmId`, `zoneId`, `name`, `fastestName`, `fastestPartySize`, `fastestTime`, `timeLimit`, `levelCap`, `partySize`, `lootDropId`, `rules`, `isMission`) VALUES(481, 203, 'class_reunion', 'nobody', 0, 1800, 1800, 99, 18, 0, 5, 0);
INSERT INTO `bcnm_info` (`bcnmId`, `zoneId`, `name`, `fastestName`, `fastestPartySize`, `fastestTime`, `timeLimit`, `levelCap`, `partySize`, `lootDropId`, `rules`, `isMission`) VALUES(482, 203, 'trial-size_trial_by_ice', 'nobody', 0, 900, 900, 20, 1, 0, 5, 0);
INSERT INTO `bcnm_info` (`bcnmId`, `zoneId`, `name`, `fastestName`, `fastestPartySize`, `fastestTime`, `timeLimit`, `levelCap`, `partySize`, `lootDropId`, `rules`, `isMission`) VALUES(483, 203, 'waking_the_beast', 'nobody', 0, 1800, 1800, 0, 18, 0, 5, 0);
INSERT INTO `bcnm_info` (`bcnmId`, `zoneId`, `name`, `fastestName`, `fastestPartySize`, `fastestTime`, `timeLimit`, `levelCap`, `partySize`, `lootDropId`, `rules`, `isMission`) VALUES(484, 203, 'sugar-coated_directive', 'nobody', 0, 1800, 1800, 99, 6, 0, 5, 0);
INSERT INTO `bcnm_info` (`bcnmId`, `zoneId`, `name`, `fastestName`, `fastestPartySize`, `fastestTime`, `timeLimit`, `levelCap`, `partySize`, `lootDropId`, `rules`, `isMission`) VALUES(512, 206, 'rank_5_mission', 'nobody', 0, 900, 900, 50, 6, 0, 5, 1);
INSERT INTO `bcnm_info` (`bcnmId`, `zoneId`, `name`, `fastestName`, `fastestPartySize`, `fastestTime`, `timeLimit`, `levelCap`, `partySize`, `lootDropId`, `rules`, `isMission`) VALUES(513, 206, 'come_into_my_parlor', 'nobody', 0, 1800, 1800, 0, 6, 513, 15, 0);
INSERT INTO `bcnm_info` (`bcnmId`, `zoneId`, `name`, `fastestName`, `fastestPartySize`, `fastestTime`, `timeLimit`, `levelCap`, `partySize`, `lootDropId`, `rules`, `isMission`) VALUES(514, 206, 'e-vase-ive_action', 'nobody', 0, 1800, 1800, 0, 6, 514, 15, 0);
INSERT INTO `bcnm_info` (`bcnmId`, `zoneId`, `name`, `fastestName`, `fastestPartySize`, `fastestTime`, `timeLimit`, `levelCap`, `partySize`, `lootDropId`, `rules`, `isMission`) VALUES(515, 206, 'infernal_swarm', 'nobody', 0, 1800, 1800, 0, 6, 515, 15, 0);
INSERT INTO `bcnm_info` (`bcnmId`, `zoneId`, `name`, `fastestName`, `fastestPartySize`, `fastestTime`, `timeLimit`, `levelCap`, `partySize`, `lootDropId`, `rules`, `isMission`) VALUES(516, 206, 'heir_to_the_light', 'nobody', 0, 1800, 1800, 75, 6, 0, 5, 1);
INSERT INTO `bcnm_info` (`bcnmId`, `zoneId`, `name`, `fastestName`, `fastestPartySize`, `fastestTime`, `timeLimit`, `levelCap`, `partySize`, `lootDropId`, `rules`, `isMission`) VALUES(517, 206, 'shattering_stars', 'nobody', 0, 600, 600, 99, 1, 0, 22, 0);
INSERT INTO `bcnm_info` (`bcnmId`, `zoneId`, `name`, `fastestName`, `fastestPartySize`, `fastestTime`, `timeLimit`, `levelCap`, `partySize`, `lootDropId`, `rules`, `isMission`) VALUES(518, 206, 'shattering_stars', 'nobody', 0, 600, 600, 99, 1, 0, 22, 0);
INSERT INTO `bcnm_info` (`bcnmId`, `zoneId`, `name`, `fastestName`, `fastestPartySize`, `fastestTime`, `timeLimit`, `levelCap`, `partySize`, `lootDropId`, `rules`, `isMission`) VALUES(519, 206, 'shattering_stars', 'nobody', 0, 600, 600, 99, 1, 0, 22, 0);
INSERT INTO `bcnm_info` (`bcnmId`, `zoneId`, `name`, `fastestName`, `fastestPartySize`, `fastestTime`, `timeLimit`, `levelCap`, `partySize`, `lootDropId`, `rules`, `isMission`) VALUES(520, 206, 'demolition_squad', 'nobody', 0, 1800, 1800, 60, 6, 520, 15, 0);
INSERT INTO `bcnm_info` (`bcnmId`, `zoneId`, `name`, `fastestName`, `fastestPartySize`, `fastestTime`, `timeLimit`, `levelCap`, `partySize`, `lootDropId`, `rules`, `isMission`) VALUES(521, 206, 'die_by_the_sword', 'nobody', 0, 900, 900, 30, 3, 521, 15, 0);
INSERT INTO `bcnm_info` (`bcnmId`, `zoneId`, `name`, `fastestName`, `fastestPartySize`, `fastestTime`, `timeLimit`, `levelCap`, `partySize`, `lootDropId`, `rules`, `isMission`) VALUES(522, 206, 'let_sleeping_dogs_die', 'nobody', 0, 1800, 1800, 30, 6, 522, 15, 0);
INSERT INTO `bcnm_info` (`bcnmId`, `zoneId`, `name`, `fastestName`, `fastestPartySize`, `fastestTime`, `timeLimit`, `levelCap`, `partySize`, `lootDropId`, `rules`, `isMission`) VALUES(523, 206, 'brothers_d_aurphe', 'nobody', 0, 1800, 1800, 60, 6, 523, 15, 0);
INSERT INTO `bcnm_info` (`bcnmId`, `zoneId`, `name`, `fastestName`, `fastestPartySize`, `fastestTime`, `timeLimit`, `levelCap`, `partySize`, `lootDropId`, `rules`, `isMission`) VALUES(524, 206, 'undying_promise', 'nobody', 0, 900, 900, 40, 3, 524, 15, 0);
INSERT INTO `bcnm_info` (`bcnmId`, `zoneId`, `name`, `fastestName`, `fastestPartySize`, `fastestTime`, `timeLimit`, `levelCap`, `partySize`, `lootDropId`, `rules`, `isMission`) VALUES(525, 206, 'factory_rejects', 'nobody', 0, 1800, 1800, 40, 6, 525, 15, 0);
INSERT INTO `bcnm_info` (`bcnmId`, `zoneId`, `name`, `fastestName`, `fastestPartySize`, `fastestTime`, `timeLimit`, `levelCap`, `partySize`, `lootDropId`, `rules`, `isMission`) VALUES(526, 206, 'idol_thoughts', 'nobody', 0, 1800, 1800, 50, 6, 526, 15, 0);
INSERT INTO `bcnm_info` (`bcnmId`, `zoneId`, `name`, `fastestName`, `fastestPartySize`, `fastestTime`, `timeLimit`, `levelCap`, `partySize`, `lootDropId`, `rules`, `isMission`) VALUES(527, 206, 'awful_autopsy', 'nobody', 0, 900, 900, 50, 3, 527, 15, 0);
INSERT INTO `bcnm_info` (`bcnmId`, `zoneId`, `name`, `fastestName`, `fastestPartySize`, `fastestTime`, `timeLimit`, `levelCap`, `partySize`, `lootDropId`, `rules`, `isMission`) VALUES(528, 206, 'celery', 'nobody', 0, 900, 900, 60, 3, 528, 15, 0);
INSERT INTO `bcnm_info` (`bcnmId`, `zoneId`, `name`, `fastestName`, `fastestPartySize`, `fastestTime`, `timeLimit`, `levelCap`, `partySize`, `lootDropId`, `rules`, `isMission`) VALUES(529, 206, 'mirror_images', 'nobody', 0, 900, 900, 50, 1, 0, 7, 0);
INSERT INTO `bcnm_info` (`bcnmId`, `zoneId`, `name`, `fastestName`, `fastestPartySize`, `fastestTime`, `timeLimit`, `levelCap`, `partySize`, `lootDropId`, `rules`, `isMission`) VALUES(530, 206, 'furious_finale', 'nobody', 0, 600, 600, 99, 1, 0, 6, 0);
INSERT INTO `bcnm_info` (`bcnmId`, `zoneId`, `name`, `fastestName`, `fastestPartySize`, `fastestTime`, `timeLimit`, `levelCap`, `partySize`, `lootDropId`, `rules`, `isMission`) VALUES(531, 206, 'clash_of_the_comrades', 'nobody', 0, 600, 600, 0, 1, 0, 7, 0);
INSERT INTO `bcnm_info` (`bcnmId`, `zoneId`, `name`, `fastestName`, `fastestPartySize`, `fastestTime`, `timeLimit`, `levelCap`, `partySize`, `lootDropId`, `rules`, `isMission`) VALUES(532, 206, 'those_who_lurk_in_shadows', 'nobody', 0, 1800, 1800, 75, 6, 0, 5, 1);
INSERT INTO `bcnm_info` (`bcnmId`, `zoneId`, `name`, `fastestName`, `fastestPartySize`, `fastestTime`, `timeLimit`, `levelCap`, `partySize`, `lootDropId`, `rules`, `isMission`) VALUES(533, 206, 'beyond_infinity', 'nobody', 0, 600, 600, 0, 6, 0, 6, 0);
INSERT INTO `bcnm_info` (`bcnmId`, `zoneId`, `name`, `fastestName`, `fastestPartySize`, `fastestTime`, `timeLimit`, `levelCap`, `partySize`, `lootDropId`, `rules`, `isMission`) VALUES(544, 207, 'trial_by_fire', 'nobody', 0, 1800, 1800, 0, 6, 0, 5, 0);
INSERT INTO `bcnm_info` (`bcnmId`, `zoneId`, `name`, `fastestName`, `fastestPartySize`, `fastestTime`, `timeLimit`, `levelCap`, `partySize`, `lootDropId`, `rules`, `isMission`) VALUES(545, 207, 'trial-size_trial_by_fire', 'nobody', 0, 900, 900, 20, 1, 0, 5, 0);
INSERT INTO `bcnm_info` (`bcnmId`, `zoneId`, `name`, `fastestName`, `fastestPartySize`, `fastestTime`, `timeLimit`, `levelCap`, `partySize`, `lootDropId`, `rules`, `isMission`) VALUES(546, 207, 'waking_the_beast', 'nobody', 0, 1800, 1800, 0, 18, 0, 5, 0);
INSERT INTO `bcnm_info` (`bcnmId`, `zoneId`, `name`, `fastestName`, `fastestPartySize`, `fastestTime`, `timeLimit`, `levelCap`, `partySize`, `lootDropId`, `rules`, `isMission`) VALUES(547, 207, 'sugar-coated_directive', 'nobody', 0, 1800, 1800, 99, 6, 0, 5, 0);
INSERT INTO `bcnm_info` (`bcnmId`, `zoneId`, `name`, `fastestName`, `fastestPartySize`, `fastestTime`, `timeLimit`, `levelCap`, `partySize`, `lootDropId`, `rules`, `isMission`) VALUES(576, 209, 'trial_by_earth', 'nobody', 0, 1800, 1800, 0, 6, 0, 5, 0);
INSERT INTO `bcnm_info` (`bcnmId`, `zoneId`, `name`, `fastestName`, `fastestPartySize`, `fastestTime`, `timeLimit`, `levelCap`, `partySize`, `lootDropId`, `rules`, `isMission`) VALUES(577, 209, 'puppet_master', 'nobody', 0, 1800, 1800, 99, 18, 0, 5, 0);
INSERT INTO `bcnm_info` (`bcnmId`, `zoneId`, `name`, `fastestName`, `fastestPartySize`, `fastestTime`, `timeLimit`, `levelCap`, `partySize`, `lootDropId`, `rules`, `isMission`) VALUES(578, 209, 'trial-size_trial_by_earth', 'nobody', 0, 900, 900, 20, 1, 0, 5, 0);
INSERT INTO `bcnm_info` (`bcnmId`, `zoneId`, `name`, `fastestName`, `fastestPartySize`, `fastestTime`, `timeLimit`, `levelCap`, `partySize`, `lootDropId`, `rules`, `isMission`) VALUES(579, 209, 'waking_the_beast', 'nobody', 0, 1800, 1800, 0, 18, 0, 5, 0);
INSERT INTO `bcnm_info` (`bcnmId`, `zoneId`, `name`, `fastestName`, `fastestPartySize`, `fastestTime`, `timeLimit`, `levelCap`, `partySize`, `lootDropId`, `rules`, `isMission`) VALUES(580, 209, 'sugar-coated_directive', 'nobody', 0, 1800, 1800, 99, 6, 0, 5, 0);
INSERT INTO `bcnm_info` (`bcnmId`, `zoneId`, `name`, `fastestName`, `fastestPartySize`, `fastestTime`, `timeLimit`, `levelCap`, `partySize`, `lootDropId`, `rules`, `isMission`) VALUES(608, 211, 'trial_by_water', 'nobody', 0, 1800, 1800, 0, 6, 0, 5, 0);
INSERT INTO `bcnm_info` (`bcnmId`, `zoneId`, `name`, `fastestName`, `fastestPartySize`, `fastestTime`, `timeLimit`, `levelCap`, `partySize`, `lootDropId`, `rules`, `isMission`) VALUES(609, 211, 'trial-size_trial_by_water', 'nobody', 0, 900, 900, 20, 1, 0, 5, 0);
INSERT INTO `bcnm_info` (`bcnmId`, `zoneId`, `name`, `fastestName`, `fastestPartySize`, `fastestTime`, `timeLimit`, `levelCap`, `partySize`, `lootDropId`, `rules`, `isMission`) VALUES(610, 211, 'waking_the_beast', 'nobody', 0, 1800, 1800, 0, 18, 0, 5, 0);
INSERT INTO `bcnm_info` (`bcnmId`, `zoneId`, `name`, `fastestName`, `fastestPartySize`, `fastestTime`, `timeLimit`, `levelCap`, `partySize`, `lootDropId`, `rules`, `isMission`) VALUES(611, 211, 'sugar-coated_directive', 'nobody', 0, 1800, 1800, 99, 6, 0, 5, 0);
INSERT INTO `bcnm_info` (`bcnmId`, `zoneId`, `name`, `fastestName`, `fastestPartySize`, `fastestTime`, `timeLimit`, `levelCap`, `partySize`, `lootDropId`, `rules`, `isMission`) VALUES(640, 6, 'flames_for_the_dead', 'nobody', 0, 1800, 1800, 60, 6, 0, 5, 0);
INSERT INTO `bcnm_info` (`bcnmId`, `zoneId`, `name`, `fastestName`, `fastestPartySize`, `fastestTime`, `timeLimit`, `levelCap`, `partySize`, `lootDropId`, `rules`, `isMission`) VALUES(641, 6, 'follow_the_white_rabbit', 'nobody', 0, 1800, 1800, 75, 18, 641, 15, 0);
INSERT INTO `bcnm_info` (`bcnmId`, `zoneId`, `name`, `fastestName`, `fastestPartySize`, `fastestTime`, `timeLimit`, `levelCap`, `partySize`, `lootDropId`, `rules`, `isMission`) VALUES(642, 6, 'when_hell_freezes_over', 'nobody', 0, 900, 900, 75, 18, 642, 15, 0);
INSERT INTO `bcnm_info` (`bcnmId`, `zoneId`, `name`, `fastestName`, `fastestPartySize`, `fastestTime`, `timeLimit`, `levelCap`, `partySize`, `lootDropId`, `rules`, `isMission`) VALUES(643, 6, 'brothers', 'nobody', 0, 1800, 1800, 75, 18, 643, 15, 0);
INSERT INTO `bcnm_info` (`bcnmId`, `zoneId`, `name`, `fastestName`, `fastestPartySize`, `fastestTime`, `timeLimit`, `levelCap`, `partySize`, `lootDropId`, `rules`, `isMission`) VALUES(644, 6, 'holy_cow', 'nobody', 0, 1800, 1800, 75, 18, 644, 15, 0);
INSERT INTO `bcnm_info` (`bcnmId`, `zoneId`, `name`, `fastestName`, `fastestPartySize`, `fastestTime`, `timeLimit`, `levelCap`, `partySize`, `lootDropId`, `rules`, `isMission`) VALUES(672, 8, 'head_wind', 'nobody', 0, 1800, 1800, 50, 6, 0, 5, 1);
INSERT INTO `bcnm_info` (`bcnmId`, `zoneId`, `name`, `fastestName`, `fastestPartySize`, `fastestTime`, `timeLimit`, `levelCap`, `partySize`, `lootDropId`, `rules`, `isMission`) VALUES(673, 8, 'like_the_wind', 'nobody', 0, 900, 900, 75, 18, 673, 15, 0);
INSERT INTO `bcnm_info` (`bcnmId`, `zoneId`, `name`, `fastestName`, `fastestPartySize`, `fastestTime`, `timeLimit`, `levelCap`, `partySize`, `lootDropId`, `rules`, `isMission`) VALUES(674, 8, 'sheep_in_antlions_clothing', 'nobody', 0, 900, 900, 75, 18, 674, 15, 0);
INSERT INTO `bcnm_info` (`bcnmId`, `zoneId`, `name`, `fastestName`, `fastestPartySize`, `fastestTime`, `timeLimit`, `levelCap`, `partySize`, `lootDropId`, `rules`, `isMission`) VALUES(675, 8, 'shell_we_dance', 'nobody', 0, 1800, 1800, 75, 18, 675, 15, 0);
INSERT INTO `bcnm_info` (`bcnmId`, `zoneId`, `name`, `fastestName`, `fastestPartySize`, `fastestTime`, `timeLimit`, `levelCap`, `partySize`, `lootDropId`, `rules`, `isMission`) VALUES(676, 8, 'totentanz', 'nobody', 0, 1800, 1800, 75, 18, 676, 15, 0);
INSERT INTO `bcnm_info` (`bcnmId`, `zoneId`, `name`, `fastestName`, `fastestPartySize`, `fastestTime`, `timeLimit`, `levelCap`, `partySize`, `lootDropId`, `rules`, `isMission`) VALUES(677, 8, 'tango_with_a_tracker', 'nobody', 0, 1800, 1800, 0, 6, 0, 7, 0);
INSERT INTO `bcnm_info` (`bcnmId`, `zoneId`, `name`, `fastestName`, `fastestPartySize`, `fastestTime`, `timeLimit`, `levelCap`, `partySize`, `lootDropId`, `rules`, `isMission`) VALUES(678, 8, 'requiem_of_a_sin', 'nobody', 0, 1800, 1800, 0, 6, 0, 7, 0);
INSERT INTO `bcnm_info` (`bcnmId`, `zoneId`, `name`, `fastestName`, `fastestPartySize`, `fastestTime`, `timeLimit`, `levelCap`, `partySize`, `lootDropId`, `rules`, `isMission`) VALUES(679, 8, 'antagonistic_ambuscade', 'nobody', 0, 900, 900, 0, 6, 679, 15, 0);
INSERT INTO `bcnm_info` (`bcnmId`, `zoneId`, `name`, `fastestName`, `fastestPartySize`, `fastestTime`, `timeLimit`, `levelCap`, `partySize`, `lootDropId`, `rules`, `isMission`) VALUES(704, 10, 'darkness_named', 'nobody', 0, 1800, 1800, 40, 6, 0, 5, 1);
INSERT INTO `bcnm_info` (`bcnmId`, `zoneId`, `name`, `fastestName`, `fastestPartySize`, `fastestTime`, `timeLimit`, `levelCap`, `partySize`, `lootDropId`, `rules`, `isMission`) VALUES(705, 10, 'test_your_mite', 'nobody', 0, 1800, 1800, 40, 18, 705, 15, 0);
INSERT INTO `bcnm_info` (`bcnmId`, `zoneId`, `name`, `fastestName`, `fastestPartySize`, `fastestTime`, `timeLimit`, `levelCap`, `partySize`, `lootDropId`, `rules`, `isMission`) VALUES(706, 10, 'waking_dreams', 'nobody', 0, 1800, 1800, 0, 18, 0, 5, 0);
INSERT INTO `bcnm_info` (`bcnmId`, `zoneId`, `name`, `fastestName`, `fastestPartySize`, `fastestTime`, `timeLimit`, `levelCap`, `partySize`, `lootDropId`, `rules`, `isMission`) VALUES(736, 13, 'century_of_hardship', 'nobody', 0, 1800, 1800, 60, 6, 0, 5, 1);
INSERT INTO `bcnm_info` (`bcnmId`, `zoneId`, `name`, `fastestName`, `fastestPartySize`, `fastestTime`, `timeLimit`, `levelCap`, `partySize`, `lootDropId`, `rules`, `isMission`) VALUES(737, 13, 'return_to_the_depths', 'nobody', 0, 1800, 1800, 99, 6, 0, 7, 0);
INSERT INTO `bcnm_info` (`bcnmId`, `zoneId`, `name`, `fastestName`, `fastestPartySize`, `fastestTime`, `timeLimit`, `levelCap`, `partySize`, `lootDropId`, `rules`, `isMission`) VALUES(738, 13, 'bionic_bug', 'nobody', 0, 1800, 1800, 0, 18, 738, 15, 0);
INSERT INTO `bcnm_info` (`bcnmId`, `zoneId`, `name`, `fastestName`, `fastestPartySize`, `fastestTime`, `timeLimit`, `levelCap`, `partySize`, `lootDropId`, `rules`, `isMission`) VALUES(739, 13, 'pulling_the_strings', 'nobody', 0, 900, 900, 0, 1, 739, 15, 0);
INSERT INTO `bcnm_info` (`bcnmId`, `zoneId`, `name`, `fastestName`, `fastestPartySize`, `fastestTime`, `timeLimit`, `levelCap`, `partySize`, `lootDropId`, `rules`, `isMission`) VALUES(740, 13, 'automaton_assault', 'nobody', 0, 900, 900, 60, 6, 740, 15, 0);
INSERT INTO `bcnm_info` (`bcnmId`, `zoneId`, `name`, `fastestName`, `fastestPartySize`, `fastestTime`, `timeLimit`, `levelCap`, `partySize`, `lootDropId`, `rules`, `isMission`) VALUES(741, 13, 'mobline_comedy', 'nobody', 0, 900, 900, 0, 6, 741, 15, 0);
INSERT INTO `bcnm_info` (`bcnmId`, `zoneId`, `name`, `fastestName`, `fastestPartySize`, `fastestTime`, `timeLimit`, `levelCap`, `partySize`, `lootDropId`, `rules`, `isMission`) VALUES(768, 17, 'ancient_flames_beckon', 'nobody', 0, 1800, 1800, 30, 6, 0, 5, 1);
INSERT INTO `bcnm_info` (`bcnmId`, `zoneId`, `name`, `fastestName`, `fastestPartySize`, `fastestTime`, `timeLimit`, `levelCap`, `partySize`, `lootDropId`, `rules`, `isMission`) VALUES(769, 17, 'simulant', 'nobody', 0, 1800, 1800, 30, 18, 769, 15, 0);
INSERT INTO `bcnm_info` (`bcnmId`, `zoneId`, `name`, `fastestName`, `fastestPartySize`, `fastestTime`, `timeLimit`, `levelCap`, `partySize`, `lootDropId`, `rules`, `isMission`) VALUES(770, 17, 'empty_hopes', 'nobody', 0, 900, 900, 0, 6, 0, 5, 0);
INSERT INTO `bcnm_info` (`bcnmId`, `zoneId`, `name`, `fastestName`, `fastestPartySize`, `fastestTime`, `timeLimit`, `levelCap`, `partySize`, `lootDropId`, `rules`, `isMission`) VALUES(800, 19, 'ancient_flames_beckon', 'nobody', 0, 1800, 1800, 30, 6, 0, 5, 1);
INSERT INTO `bcnm_info` (`bcnmId`, `zoneId`, `name`, `fastestName`, `fastestPartySize`, `fastestTime`, `timeLimit`, `levelCap`, `partySize`, `lootDropId`, `rules`, `isMission`) VALUES(801, 19, 'you_are_what_you_eat', 'nobody', 0, 1800, 1800, 30, 18, 801, 15, 0);
INSERT INTO `bcnm_info` (`bcnmId`, `zoneId`, `name`, `fastestName`, `fastestPartySize`, `fastestTime`, `timeLimit`, `levelCap`, `partySize`, `lootDropId`, `rules`, `isMission`) VALUES(802, 19, 'empty_dreams', 'nobody', 0, 900, 900, 0, 6, 0, 5, 0);
INSERT INTO `bcnm_info` (`bcnmId`, `zoneId`, `name`, `fastestName`, `fastestPartySize`, `fastestTime`, `timeLimit`, `levelCap`, `partySize`, `lootDropId`, `rules`, `isMission`) VALUES(832, 21, 'ancient_flames_beckon', 'nobody', 0, 1800, 1800, 30, 6, 0, 5, 1);
INSERT INTO `bcnm_info` (`bcnmId`, `zoneId`, `name`, `fastestName`, `fastestPartySize`, `fastestTime`, `timeLimit`, `levelCap`, `partySize`, `lootDropId`, `rules`, `isMission`) VALUES(833, 21, 'playing_host', 'nobody', 0, 1800, 1800, 30, 18, 833, 15, 0);
INSERT INTO `bcnm_info` (`bcnmId`, `zoneId`, `name`, `fastestName`, `fastestPartySize`, `fastestTime`, `timeLimit`, `levelCap`, `partySize`, `lootDropId`, `rules`, `isMission`) VALUES(834, 21, 'empty_desires', 'nobody', 0, 900, 900, 0, 6, 0, 5, 0);
INSERT INTO `bcnm_info` (`bcnmId`, `zoneId`, `name`, `fastestName`, `fastestPartySize`, `fastestTime`, `timeLimit`, `levelCap`, `partySize`, `lootDropId`, `rules`, `isMission`) VALUES(864, 23, 'desires_of_emptiness', 'nobody', 0, 1800, 1800, 50, 6, 0, 5, 1);
INSERT INTO `bcnm_info` (`bcnmId`, `zoneId`, `name`, `fastestName`, `fastestPartySize`, `fastestTime`, `timeLimit`, `levelCap`, `partySize`, `lootDropId`, `rules`, `isMission`) VALUES(865, 23, 'pulling_the_plug', 'nobody', 0, 1800, 1800, 50, 18, 865, 15, 0);
INSERT INTO `bcnm_info` (`bcnmId`, `zoneId`, `name`, `fastestName`, `fastestPartySize`, `fastestTime`, `timeLimit`, `levelCap`, `partySize`, `lootDropId`, `rules`, `isMission`) VALUES(866, 23, 'empty_aspirations', 'nobody', 0, 900, 900, 0, 6, 0, 5, 0);
INSERT INTO `bcnm_info` (`bcnmId`, `zoneId`, `name`, `fastestName`, `fastestPartySize`, `fastestTime`, `timeLimit`, `levelCap`, `partySize`, `lootDropId`, `rules`, `isMission`) VALUES(896, 29, 'storms_of_fate', 'nobody', 0, 1800, 1800, 0, 18, 0, 7, 0);
INSERT INTO `bcnm_info` (`bcnmId`, `zoneId`, `name`, `fastestName`, `fastestPartySize`, `fastestTime`, `timeLimit`, `levelCap`, `partySize`, `lootDropId`, `rules`, `isMission`) VALUES(897, 29, 'wyrmking_descends', 'nobody', 0, 3600, 3600, 0, 18, 0, 7, 0);
INSERT INTO `bcnm_info` (`bcnmId`, `zoneId`, `name`, `fastestName`, `fastestPartySize`, `fastestTime`, `timeLimit`, `levelCap`, `partySize`, `lootDropId`, `rules`, `isMission`) VALUES(928, 30, 'ouryu_cometh', 'nobody', 0, 3600, 3600, 0, 18, 0, 7, 0);
INSERT INTO `bcnm_info` (`bcnmId`, `zoneId`, `name`, `fastestName`, `fastestPartySize`, `fastestTime`, `timeLimit`, `levelCap`, `partySize`, `lootDropId`, `rules`, `isMission`) VALUES(960, 31, 'ancient_vows', 'nobody', 0, 1800, 1800, 40, 6, 0, 5, 1);
INSERT INTO `bcnm_info` (`bcnmId`, `zoneId`, `name`, `fastestName`, `fastestPartySize`, `fastestTime`, `timeLimit`, `levelCap`, `partySize`, `lootDropId`, `rules`, `isMission`) VALUES(961, 31, 'savage', 'nobody', 0, 1800, 1800, 50, 6, 0, 5, 1);
INSERT INTO `bcnm_info` (`bcnmId`, `zoneId`, `name`, `fastestName`, `fastestPartySize`, `fastestTime`, `timeLimit`, `levelCap`, `partySize`, `lootDropId`, `rules`, `isMission`) VALUES(962, 31, 'fire_in_the_sky', 'nobody', 0, 900, 900, 40, 18, 962, 15, 0);
INSERT INTO `bcnm_info` (`bcnmId`, `zoneId`, `name`, `fastestName`, `fastestPartySize`, `fastestTime`, `timeLimit`, `levelCap`, `partySize`, `lootDropId`, `rules`, `isMission`) VALUES(963, 31, 'bad_seed', 'nobody', 0, 1800, 1800, 40, 18, 963, 15, 0);
INSERT INTO `bcnm_info` (`bcnmId`, `zoneId`, `name`, `fastestName`, `fastestPartySize`, `fastestTime`, `timeLimit`, `levelCap`, `partySize`, `lootDropId`, `rules`, `isMission`) VALUES(964, 31, 'bugard_in_the_clouds', 'nobody', 0, 900, 900, 50, 18, 964, 15, 0);
INSERT INTO `bcnm_info` (`bcnmId`, `zoneId`, `name`, `fastestName`, `fastestPartySize`, `fastestTime`, `timeLimit`, `levelCap`, `partySize`, `lootDropId`, `rules`, `isMission`) VALUES(965, 31, 'beloved_of_the_atlantes', 'nobody', 0, 1800, 1800, 50, 18, 965, 15, 0);
INSERT INTO `bcnm_info` (`bcnmId`, `zoneId`, `name`, `fastestName`, `fastestPartySize`, `fastestTime`, `timeLimit`, `levelCap`, `partySize`, `lootDropId`, `rules`, `isMission`) VALUES(966, 31, 'uninvited_guests', 'nobody', 0, 1800, 1800, 0, 18, 0, 7, 0);
INSERT INTO `bcnm_info` (`bcnmId`, `zoneId`, `name`, `fastestName`, `fastestPartySize`, `fastestTime`, `timeLimit`, `levelCap`, `partySize`, `lootDropId`, `rules`, `isMission`) VALUES(967, 31, 'nest_of_nightmares', 'nobody', 0, 900, 900, 0, 6, 967, 15, 0);
INSERT INTO `bcnm_info` (`bcnmId`, `zoneId`, `name`, `fastestName`, `fastestPartySize`, `fastestTime`, `timeLimit`, `levelCap`, `partySize`, `lootDropId`, `rules`, `isMission`) VALUES(992, 32, 'one_to_be_feared', 'nobody', 0, 2700, 2700, 60, 6, 0, 5, 1);
INSERT INTO `bcnm_info` (`bcnmId`, `zoneId`, `name`, `fastestName`, `fastestPartySize`, `fastestTime`, `timeLimit`, `levelCap`, `partySize`, `lootDropId`, `rules`, `isMission`) VALUES(993, 32, 'warriors_path', 'nobody', 0, 1800, 1800, 75, 6, 0, 5, 1);
INSERT INTO `bcnm_info` (`bcnmId`, `zoneId`, `name`, `fastestName`, `fastestPartySize`, `fastestTime`, `timeLimit`, `levelCap`, `partySize`, `lootDropId`, `rules`, `isMission`) VALUES(1024, 35, 'when_angels_fall', 'nobody', 0, 1800, 1800, 75, 6, 0, 5, 1);
INSERT INTO `bcnm_info` (`bcnmId`, `zoneId`, `name`, `fastestName`, `fastestPartySize`, `fastestTime`, `timeLimit`, `levelCap`, `partySize`, `lootDropId`, `rules`, `isMission`) VALUES(1056, 36, 'dawn', 'nobody', 0, 1800, 1800, 75, 6, 0, 5, 1);
INSERT INTO `bcnm_info` (`bcnmId`, `zoneId`, `name`, `fastestName`, `fastestPartySize`, `fastestTime`, `timeLimit`, `levelCap`, `partySize`, `lootDropId`, `rules`, `isMission`) VALUES(1057, 36, 'apocalypse_nigh', 'nobody', 0, 1800, 1800, 75, 6, 0, 7, 0);
INSERT INTO `bcnm_info` (`bcnmId`, `zoneId`, `name`, `fastestName`, `fastestPartySize`, `fastestTime`, `timeLimit`, `levelCap`, `partySize`, `lootDropId`, `rules`, `isMission`) VALUES(1088, 57, 'call_to_arms', 'nobody', 0, 1800, 1800, 60, 6, 1088, 15, 0);
INSERT INTO `bcnm_info` (`bcnmId`, `zoneId`, `name`, `fastestName`, `fastestPartySize`, `fastestTime`, `timeLimit`, `levelCap`, `partySize`, `lootDropId`, `rules`, `isMission`) VALUES(1089, 57, 'compliments_to_the_chef', 'nobody', 0, 1800, 1800, 75, 6, 1089, 15, 0);
INSERT INTO `bcnm_info` (`bcnmId`, `zoneId`, `name`, `fastestName`, `fastestPartySize`, `fastestTime`, `timeLimit`, `levelCap`, `partySize`, `lootDropId`, `rules`, `isMission`) VALUES(1090, 57, 'puppetmaster_blues', 'nobody', 0, 1800, 1800, 75, 6, 0, 7, 0);
INSERT INTO `bcnm_info` (`bcnmId`, `zoneId`, `name`, `fastestName`, `fastestPartySize`, `fastestTime`, `timeLimit`, `levelCap`, `partySize`, `lootDropId`, `rules`, `isMission`) VALUES(1091, 57, 'breaking_the_bonds_of_fate', 'nobody', 0, 600, 600, 99, 1, 0, 6, 0);
INSERT INTO `bcnm_info` (`bcnmId`, `zoneId`, `name`, `fastestName`, `fastestPartySize`, `fastestTime`, `timeLimit`, `levelCap`, `partySize`, `lootDropId`, `rules`, `isMission`) VALUES(1092, 57, 'legacy_of_the_lost', 'nobody', 0, 1800, 1800, 99, 6, 0, 5, 0);
INSERT INTO `bcnm_info` (`bcnmId`, `zoneId`, `name`, `fastestName`, `fastestPartySize`, `fastestTime`, `timeLimit`, `levelCap`, `partySize`, `lootDropId`, `rules`, `isMission`) VALUES(1120, 64, 'tough_nut_to_crack', 'nobody', 0, 1800, 1800, 60, 6, 1120, 15, 0);
INSERT INTO `bcnm_info` (`bcnmId`, `zoneId`, `name`, `fastestName`, `fastestPartySize`, `fastestTime`, `timeLimit`, `levelCap`, `partySize`, `lootDropId`, `rules`, `isMission`) VALUES(1121, 64, 'happy_caster', 'nobody', 0, 1800, 1800, 75, 6, 1121, 15, 0);
INSERT INTO `bcnm_info` (`bcnmId`, `zoneId`, `name`, `fastestName`, `fastestPartySize`, `fastestTime`, `timeLimit`, `levelCap`, `partySize`, `lootDropId`, `rules`, `isMission`) VALUES(1122, 64, 'omens', 'nobody', 0, 1800, 1800, 0, 18, 0, 7, 0);
INSERT INTO `bcnm_info` (`bcnmId`, `zoneId`, `name`, `fastestName`, `fastestPartySize`, `fastestTime`, `timeLimit`, `levelCap`, `partySize`, `lootDropId`, `rules`, `isMission`) VALUES(1123, 64, 'achieving_true_power', 'nobody', 0, 600, 600, 99, 1, 0, 6, 0);
INSERT INTO `bcnm_info` (`bcnmId`, `zoneId`, `name`, `fastestName`, `fastestPartySize`, `fastestTime`, `timeLimit`, `levelCap`, `partySize`, `lootDropId`, `rules`, `isMission`) VALUES(1124, 64, 'shield_of_diplomacy', 'nobody', 0, 1800, 1800, 99, 6, 0, 5, 0);
INSERT INTO `bcnm_info` (`bcnmId`, `zoneId`, `name`, `fastestName`, `fastestPartySize`, `fastestTime`, `timeLimit`, `levelCap`, `partySize`, `lootDropId`, `rules`, `isMission`) VALUES(1152, 67, 'making_a_mockery', 'nobody', 0, 1800, 1800, 60, 6, 1152, 15, 0);
INSERT INTO `bcnm_info` (`bcnmId`, `zoneId`, `name`, `fastestName`, `fastestPartySize`, `fastestTime`, `timeLimit`, `levelCap`, `partySize`, `lootDropId`, `rules`, `isMission`) VALUES(1153, 67, 'shadows_of_the_mind', 'nobody', 0, 1800, 1800, 90, 6, 1153, 15, 0);
INSERT INTO `bcnm_info` (`bcnmId`, `zoneId`, `name`, `fastestName`, `fastestPartySize`, `fastestTime`, `timeLimit`, `levelCap`, `partySize`, `lootDropId`, `rules`, `isMission`) VALUES(1154, 67, 'beast_within', 'nobody', 0, 600, 600, 99, 1, 0, 6, 0);
INSERT INTO `bcnm_info` (`bcnmId`, `zoneId`, `name`, `fastestName`, `fastestPartySize`, `fastestTime`, `timeLimit`, `levelCap`, `partySize`, `lootDropId`, `rules`, `isMission`) VALUES(1155, 67, 'moment_of_truth', 'nobody', 0, 1800, 1800, 0, 6, 0, 7, 0);
INSERT INTO `bcnm_info` (`bcnmId`, `zoneId`, `name`, `fastestName`, `fastestPartySize`, `fastestTime`, `timeLimit`, `levelCap`, `partySize`, `lootDropId`, `rules`, `isMission`) VALUES(1156, 67, 'puppet_in_peril', 'nobody', 0, 1800, 1800, 99, 6, 0, 5, 0);
INSERT INTO `bcnm_info` (`bcnmId`, `zoneId`, `name`, `fastestName`, `fastestPartySize`, `fastestTime`, `timeLimit`, `levelCap`, `partySize`, `lootDropId`, `rules`, `isMission`) VALUES(1184, 78, 'rider_cometh', 'nobody', 0, 900, 900, 0, 6, 0, 5, 0);
INSERT INTO `bcnm_info` (`bcnmId`, `zoneId`, `name`, `fastestName`, `fastestPartySize`, `fastestTime`, `timeLimit`, `levelCap`, `partySize`, `lootDropId`, `rules`, `isMission`) VALUES(1290, 38, 'nw_apollyon', 'nobody', 0, 1800, 1800, 0, 18, 0, 7, 0);
INSERT INTO `bcnm_info` (`bcnmId`, `zoneId`, `name`, `fastestName`, `fastestPartySize`, `fastestTime`, `timeLimit`, `levelCap`, `partySize`, `lootDropId`, `rules`, `isMission`) VALUES(1291, 38, 'sw_apollyon', 'nobody', 0, 1800, 1800, 0, 18, 0, 7, 0);
INSERT INTO `bcnm_info` (`bcnmId`, `zoneId`, `name`, `fastestName`, `fastestPartySize`, `fastestTime`, `timeLimit`, `levelCap`, `partySize`, `lootDropId`, `rules`, `isMission`) VALUES(1292, 38, 'ne_apollyon', 'nobody', 0, 1800, 1800, 0, 18, 0, 7, 0);
INSERT INTO `bcnm_info` (`bcnmId`, `zoneId`, `name`, `fastestName`, `fastestPartySize`, `fastestTime`, `timeLimit`, `levelCap`, `partySize`, `lootDropId`, `rules`, `isMission`) VALUES(1293, 38, 'se_apollyon', 'nobody', 0, 1800, 1800, 0, 18, 0, 7, 0);
INSERT INTO `bcnm_info` (`bcnmId`, `zoneId`, `name`, `fastestName`, `fastestPartySize`, `fastestTime`, `timeLimit`, `levelCap`, `partySize`, `lootDropId`, `rules`, `isMission`) VALUES(1294, 38, 'cs_apollyon', 'nobody', 0, 1200, 1200, 0, 18, 0, 7, 0);
INSERT INTO `bcnm_info` (`bcnmId`, `zoneId`, `name`, `fastestName`, `fastestPartySize`, `fastestTime`, `timeLimit`, `levelCap`, `partySize`, `lootDropId`, `rules`, `isMission`) VALUES(1295, 38, 'cs_apollyon_ii', 'nobody', 0, 1200, 1200, 0, 18, 0, 7, 0);
INSERT INTO `bcnm_info` (`bcnmId`, `zoneId`, `name`, `fastestName`, `fastestPartySize`, `fastestTime`, `timeLimit`, `levelCap`, `partySize`, `lootDropId`, `rules`, `isMission`) VALUES(1296, 38, 'central_apollyon', 'nobody', 0, 1800, 1800, 0, 18, 0, 7, 0);
INSERT INTO `bcnm_info` (`bcnmId`, `zoneId`, `name`, `fastestName`, `fastestPartySize`, `fastestTime`, `timeLimit`, `levelCap`, `partySize`, `lootDropId`, `rules`, `isMission`) VALUES(1297, 38, 'central_apollyon_ii', 'nobody', 0, 1800, 1800, 0, 18, 0, 7, 0);
INSERT INTO `bcnm_info` (`bcnmId`, `zoneId`, `name`, `fastestName`, `fastestPartySize`, `fastestTime`, `timeLimit`, `levelCap`, `partySize`, `lootDropId`, `rules`, `isMission`) VALUES(1298, 37, 'temenos_western_tower', 'nobody', 0, 1800, 1800, 0, 18, 0, 7, 0);
INSERT INTO `bcnm_info` (`bcnmId`, `zoneId`, `name`, `fastestName`, `fastestPartySize`, `fastestTime`, `timeLimit`, `levelCap`, `partySize`, `lootDropId`, `rules`, `isMission`) VALUES(1299, 37, 'temenos_northern_tower', 'nobody', 0, 1800, 1800, 0, 18, 0, 7, 0);
INSERT INTO `bcnm_info` (`bcnmId`, `zoneId`, `name`, `fastestName`, `fastestPartySize`, `fastestTime`, `timeLimit`, `levelCap`, `partySize`, `lootDropId`, `rules`, `isMission`) VALUES(1300, 37, 'temenos_eastern_tower', 'nobody', 0, 1800, 1800, 0, 18, 0, 7, 0);
INSERT INTO `bcnm_info` (`bcnmId`, `zoneId`, `name`, `fastestName`, `fastestPartySize`, `fastestTime`, `timeLimit`, `levelCap`, `partySize`, `lootDropId`, `rules`, `isMission`) VALUES(1301, 37, 'central_temenos_basement', 'nobody', 0, 900, 900, 0, 18, 0, 7, 0);
INSERT INTO `bcnm_info` (`bcnmId`, `zoneId`, `name`, `fastestName`, `fastestPartySize`, `fastestTime`, `timeLimit`, `levelCap`, `partySize`, `lootDropId`, `rules`, `isMission`) VALUES(1302, 37, 'central_temenos_basement_ii', 'nobody', 0, 900, 900, 0, 18, 0, 7, 0);
INSERT INTO `bcnm_info` (`bcnmId`, `zoneId`, `name`, `fastestName`, `fastestPartySize`, `fastestTime`, `timeLimit`, `levelCap`, `partySize`, `lootDropId`, `rules`, `isMission`) VALUES(1303, 37, 'central_temenos_1st_floor', 'nobody', 0, 2700, 2700, 0, 18, 0, 7, 0);
INSERT INTO `bcnm_info` (`bcnmId`, `zoneId`, `name`, `fastestName`, `fastestPartySize`, `fastestTime`, `timeLimit`, `levelCap`, `partySize`, `lootDropId`, `rules`, `isMission`) VALUES(1304, 37, 'central_temenos_2nd_floor', 'nobody', 0, 2700, 2700, 0, 18, 0, 7, 0);
INSERT INTO `bcnm_info` (`bcnmId`, `zoneId`, `name`, `fastestName`, `fastestPartySize`, `fastestTime`, `timeLimit`, `levelCap`, `partySize`, `lootDropId`, `rules`, `isMission`) VALUES(1305, 37, 'central_temenos_3rd_floor', 'nobody', 0, 2700, 2700, 0, 18, 0, 7, 0);
INSERT INTO `bcnm_info` (`bcnmId`, `zoneId`, `name`, `fastestName`, `fastestPartySize`, `fastestTime`, `timeLimit`, `levelCap`, `partySize`, `lootDropId`, `rules`, `isMission`) VALUES(1306, 37, 'central_temenos_4th_floor', 'nobody', 0, 3600, 3600, 0, 18, 0, 7, 0);
INSERT INTO `bcnm_info` (`bcnmId`, `zoneId`, `name`, `fastestName`, `fastestPartySize`, `fastestTime`, `timeLimit`, `levelCap`, `partySize`, `lootDropId`, `rules`, `isMission`) VALUES(1307, 37, 'central_temenos_4th_floor_ii', 'nobody', 0, 3600, 3600, 0, 18, 0, 7, 0);
INSERT INTO `bcnm_info` (`bcnmId`, `zoneId`, `name`, `fastestName`, `fastestPartySize`, `fastestTime`, `timeLimit`, `levelCap`, `partySize`, `lootDropId`, `rules`, `isMission`) VALUES(1500, 85, 'purple_the_new_black', 'nobody', 0, 1800, 1800, 0, 6, 0, 5, 1);

--
-- Indexes for dumped tables
--

--
-- Indexes for table `bcnm_info`
--
ALTER TABLE `bcnm_info`
  ADD PRIMARY KEY (`bcnmId`);
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
